[app]
name = "MyApp"
version = "2.1.0"

[server]
host = "localhost"
port = 8080

[server.ssl]
enabled = true
cert = "/path/to/cert.pem"

[database.connection]
url = "postgresql://localhost:5432/mydb"

[feature.flags]
beta = true
