series = "cpu_usage"

[[points]]
t = 1704067200
v = 45.2

[[points]]
t = 1704067260
v = 52.1

[[points]]
t = 1704067320
v = 48.7

[[points]]
t = 1704067380
v = 61.3

[[points]]
t = 1704067440
v = 55.9
